version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: marketing_sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Yashas#@123
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - marketing_network
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local

networks:
  marketing_network:
    driver: bridge