developer_token: "ouYOcEpDiQOJCTs-Rkc1mA"
client_id: "27301795624-e2iccuor7ba1shjmrt87b58f0iitf2rv.apps.googleusercontent.com"
client_secret: "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"
refresh_token: "1//0gNfC5zz1vWTMCgYIARAAGBASNwF-L9IrmkRGLiDcO72bExvzu0OsUZaZLi4kBRIM6eP3VRX2GcVPTBKihOGP1827s_rqBGvOj7o"
login_customer_id: "3341907700"
use_proto_plus: true